### ISSUE TITLE
Unable to read .meteor/versions

### ISSUE THREAD

**Issue by saksholm** [zodern/meteor-package-versions#2]
I installed `montiapm:agent`, which is dependent on this package.

Our Meteor project is not directly in the root folder and that may cause this error:

`[Unable to read .meteor/versions - ENOENT: no such file or directory, open './.meteor/versions'](zodern:meteor-package-versions: Unable to read .meteor/versions - ENOENT: no such file or directory, open './.meteor/versions')`

Is there any fix for this or is this needed to run MontiAPM properly? Maybe some root folder check.

**Comment by zodern** [comment]
> Our Meteor project is not directly in the root folder

This should be fine. I have many projects that are structured similarly.

This package expects that the `meteor` command is run from the root of the app. I had thought that Meteor requires that. Are you running `meteor` in a different folder? What would be the relative path to `.meteor/versions` from where you run `meteor`?

**Comment by saksholm** [comment]
Yeah, the problem was exactly what you mention. meteor is running on a different folder. We changed our Dockerfile and now it seems to work! Thank you!

**Comment by zodern** [comment]
@saksholm would you mind sharing what folder meteor was run in relative to the app? If you ran into this issue, other people probably have or will too so it would be nice if we could fix it.

**Comment by saksholm** [comment]
> @saksholm would you mind sharing what folder meteor was run in relative to the app? If you ran into this issue, other people probably have or will too so it would be nice if we could fix it.

Sorry for the delay. Basically our Dockerfile looked like this: 

```
FROM zcloudws/meteor-build:2.12 as builder

WORKDIR /build/source
USER root

RUN chown zcloud:zcloud -R /build

USER zcloud:zcloud
COPY --chown=zcloud:zcloud . /build/source

ENV METEOR_DISABLE_OPTIMISTIC_CACHING=1

WORKDIR /build/source/meteor

RUN meteor npm ci
RUN meteor build --directory ../../app-build

FROM zcloudws/meteor-node-mongodb-runtime:2.12
COPY --from=builder /build/app-build/bundle /home/zcloud/app

RUN cd /home/zcloud/app/programs/server && npm --no-audit install

WORKDIR /home/zcloud/app

ENV NO_NPM_INSTALL=1

ENTRYPOINT ["/scripts/startup.sh"]
```

We had other issues from the beginning with our repo and decided to make a custom Dockerfile. We got issues resolved and we stayed using the custom version. After this issue was faced, we switched the custom Dockerfile to default presets and this issue magically disappeared.
